version: "3.7"

services:
  club_app: &app
    build:
      dockerfile: Dockerfile
      context: .
    command: make docker-run-production
    container_name: club_app
    environment:
      - MODE=production
      - PYTHONUNBUFFERED=1
      - DEBUG=false
      - APP_HOST=https://rustockholm.club
      - MEDIA_UPLOAD_URL=https://i.rustockholm.club/upload/
      - POSTGRES_DB=vas3k_club
      - POSTGRES_USER=vas3k
      - POSTGRES_PASSWORD=${db_pass}
      - POSTGRES_HOST=postgres
      - REDIS_DB=0
      - REDIS_HOST=redis
      - EMAIL_HOST
      - EMAIL_PORT
      - DEFAULT_FROM_EMAIL
    restart: always
    volumes:
      - ./frontend/static:/app/frontend/static
      - ./gdpr/downloads:/app/gdpr/downloads
    depends_on:
      - postgres
      - redis
      - queue
    ports:
      - "127.0.0.1:8814:8814"

  queue:
    <<: *app
    command: make docker-run-queue
    container_name: club_queue
    depends_on:
      - postgres
      - redis
    ports: []

  bot:
    <<: *app
    command: make docker-run-bot
    container_name: club_bot
    depends_on:
      - club_app
      - postgres
      - redis
    ports:
      - "8816:8816"

  postgres:
    image: postgres:12
    container_name: club_postgres
    restart: always
    environment:
      POSTGRES_USER: vas3k
      POSTGRES_PASSWORD: ${db_pass}
      POSTGRES_DB: vas3k_club
    volumes:
      - /home/vas3k/pgdata:/var/lib/postgresql/data:rw
    ports:
      - "127.0.0.1:54333:5432"
      
  pgbackups3:
    image: schickling/postgres-backup-s3
    links:
      - postgres
    environment:
      SCHEDULE: '@daily'
      S3_REGION: fra1
      S3_ACCESS_KEY_ID: ${s3key}
      S3_SECRET_ACCESS_KEY: ${s3secret}
      S3_BUCKET: clubspace
      S3_PREFIX: backup
      POSTGRES_DATABASE: vas3k_club
      POSTGRES_USER: vas3k
      POSTGRES_PASSWORD: ${db_pass}
      POSTGRES_EXTRA_OPTS: '--schema=public --blobs'

  redis:
    image: redis:alpine
    container_name: club_redis
    restart: always
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
